version: "3.5"
services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    volumes:
      - ./server.conf.jsonc:/etc/v2ray/server.conf.jsonc
    ports:
      - "16823:16823"
      - "16823:16823/udp"
      - "10000-20000:10000-20000"
      - "10000-20000:10000-20000/udp"
    command: ["v2ray", "-config=/etc/v2ray/server.conf.jsonc"]
